Repository labring/fastgpt-plugin, pull requests merged in 2025-08, with the labels that each got.

#149 remove metaso invalid tool
  modules/tool/api/runStream.ts
  modules/tool/packages/metaso/children/metasoAsk/config.ts
  modules/tool/packages/metaso/children/metasoAsk/index.ts
  modules/tool/packages/metaso/children/metasoAsk/src/index.ts
  modules/tool/packages/metaso/children/metasoReader/config.ts
  modules/tool/packages/metaso/children/metasoReader/index.ts
  modules/tool/packages/metaso/children/metasoReader/src/index.ts
  modules/tool/packages/metaso/children/metasoSearch/config.ts
  modules/tool/packages/metaso/children/metasoSearch/src/index.ts
  modules/tool/packages/metaso/config.ts
  modules/tool/packages/metaso/src/api.ts
  modules/tool/packages/metaso/src/config.ts
  modules/tool/packages/metaso/src/index.ts
  modules/tool/packages/metaso/src/types.ts
  modules/tool/packages/metaso/src/utils.ts
  modules/tool/packages/metaso/test/integration.test.ts
Labels: size/XXL

#150 perf: remove invalid field
  modules/tool/type/api.ts
  modules/tool/utils/tool.ts
  sdk/package.json
  src/index.ts
  src/utils/signoz.ts
Labels: size/S

#151 update tool type
  modules/tool/packages/metaso/config.ts
Labels: size/XS

#154 fix: gpt5 models
  modules/model/provider/openai.ts
Labels: size/M

#158 chore: remove Bing tool package and related files
  modules/tool/packages/bing/config.ts
  modules/tool/packages/bing/index.ts
  modules/tool/packages/bing/package.json
  modules/tool/packages/bing/src/index.ts
Labels: size/L

#159 fix: doc2x
  dev_zh_CN.md
  modules/tool/packages/Doc2X/children/PDF2text/config.ts
  modules/tool/packages/Doc2X/children/PDF2text/src/index.ts
  modules/tool/packages/bocha/config.ts
  modules/tool/packages/metaso/children/metasoSearch/config.ts
  sdk/package.json
Labels: size/M

#164 fix: tool smtpEmail ssl type
  modules/tool/packages/smtpEmail/src/index.ts
Labels: size/XS

#167 perf: model provider move
  bun.lock
  modules/model/constants.ts
  modules/model/init.ts
  modules/model/provider/AliCloud/index.ts
  modules/model/provider/BAAI/index.ts
  modules/model/provider/Baichuan/index.ts
  modules/model/provider/ChatGLM/index.ts
  modules/model/provider/Claude/index.ts
  modules/model/provider/DeepSeek/index.ts
  modules/model/provider/Doubao/index.ts
  modules/model/provider/Ernie/index.ts
  modules/model/provider/FishAudio/index.ts
  modules/model/provider/Gemini/index.ts
  modules/model/provider/Grok/index.ts
  modules/model/provider/Groq/index.ts
  modules/model/provider/HuggingFace/index.ts
  modules/model/provider/Hunyuan/index.ts
  modules/model/provider/InternLM/index.ts
  modules/model/provider/Jina/index.ts
  modules/model/provider/Meta/index.ts
  modules/model/provider/MiniMax/index.ts
  modules/model/provider/MistralAI/index.ts
  modules/model/provider/Moka/index.ts
  modules/model/provider/Moonshot/index.ts
  modules/model/provider/Ollama/index.ts
  modules/model/provider/OpenAI/index.ts
  modules/model/provider/OpenRouter/index.ts
  modules/model/provider/Other/index.ts
  modules/model/provider/Other/logo.svg
  modules/model/provider/PPIO/index.ts
  modules/model/provider/Qwen/index.ts
  modules/model/provider/Siliconflow/index.ts
  modules/model/provider/SparkDesk/index.ts
  modules/model/provider/StepFun/index.ts
  modules/model/provider/Yi/index.ts
  modules/model/provider/ai360/index.ts
  modules/model/provider/novita/index.ts
  modules/tool/utils/tool.ts
  sdk/client.ts
  src/type/i18n.ts
Labels: size/XL
