Repository labring/fastgpt-plugin, pull requests merged in 2025-06, with the labels that each got.

#6 fix: type
  packages/tool/api/getTool.ts
  packages/tool/api/list.ts
  packages/tool/api/run.ts
  packages/tool/contract.ts
  packages/tool/packages/DingTalkWebhook/config.ts
  packages/tool/packages/DingTalkWebhook/src/index.ts
  packages/tool/packages/Doc2X/PDF2text/config.ts
  packages/tool/packages/WeWorkWebhook/config.ts
  packages/tool/packages/bing/config.ts
  packages/tool/packages/dalle3/config.ts
  packages/tool/packages/databaseConnection/config.ts
  packages/tool/packages/delay/config.ts
  packages/tool/packages/drawing/baseChart/config.ts
  packages/tool/packages/duckduckgo/search/config.ts
  packages/tool/packages/duckduckgo/searchImg/config.ts
  packages/tool/packages/duckduckgo/searchNews/config.ts
  packages/tool/packages/duckduckgo/searchVideo/config.ts
  packages/tool/packages/feishu/config.ts
  packages/tool/packages/fetchUrl/config.ts
  packages/tool/packages/google/config.ts
  packages/tool/packages/mathExprVal/config.ts
  packages/tool/packages/searchXNG/config.ts
  packages/tool/packages/smtpEmail/config.ts
  packages/tool/packages/wiki/config.ts
  packages/tool/type/fastgpt.ts
  packages/tool/type/index.ts
  packages/tool/type/tool.ts
  packages/tool/utils/tool.ts
Labels: size/XL

#4 Update key
  packages/tool/packages/DingTalkWebhook/config.ts
  packages/tool/packages/DingTalkWebhook/src/index.ts
  packages/tool/packages/WeWorkWebhook/config.ts
  packages/tool/packages/WeWorkWebhook/src/index.ts
  packages/tool/packages/dalle3/config.ts
  packages/tool/packages/dalle3/src/index.ts
  packages/tool/packages/drawing/baseChart/config.ts
  packages/tool/packages/drawing/baseChart/src/index.ts
  packages/tool/packages/mathExprVal/src/index.ts
  vitest.config.ts
Labels: size/L

#8 chore: update
  bun.lock
  package.json
  packages/tool/api/getTool.ts
  packages/tool/api/list.ts
  packages/tool/api/run.ts
  packages/tool/contract.ts
  packages/tool/init.ts
  packages/tool/router.ts
  scripts/build.ts
  sdk/test.ts
  src/contract/index.ts
  src/index.ts
  src/router/index.ts
  src/router/middleware/auth.ts
  src/utils/dynamicImport.ts
  src/utils/log.ts
  src/worker/index.ts
  src/worker/worker.ts
Labels: size/L

#7 img
  package.json
  packages/tool/init.ts
  packages/tool/packages/bing/icon.svg
  packages/tool/type/tool.ts
  packages/tool/utils/icon.ts
  packages/tool/utils/tool.ts
  scripts/build.ts
  scripts/dev.ts
  src/index.ts
Labels: size/L

#9 chore: add workflows
  .github/workflows/build.yml
  package.json
Labels: size/M

#16 fix: workflow get docker hub name
  .github/workflows/build.yml
Labels: size/XS

#17 chore: type
  src/worker/index.ts
  src/worker/type.ts
  src/worker/utils.ts
  src/worker/worker.d.ts
  src/worker/worker.ts
  tsconfig.json
Labels: size/L

#11 feat: add MinIO file storage service with upload and download capabilities
  .env.template
  bun.lock
  package.json
  src/s3/config.ts
  src/s3/controller.ts
  src/worker/index.ts
  src/worker/type.ts
  src/worker/utils.ts
  src/worker/worker.ts
Labels: size/L

#21 0.1 dev
  Dockerfile
  packages/tool/init.ts
  scripts/build.ts
Labels: size/S

#24 0.1 dev
  packages/tool/packages/dalle3/src/index.ts
  packages/tool/packages/drawing/children/baseChart/src/index.ts
  src/s3/controller.ts
Labels: size/M

#25 fix: openapi swagger
  .github/workflows/build-image-preview.yml
  Dockerfile
  package.json
  packages/tool/api/run.ts
  packages/tool/packages/drawing/children/baseChart/src/index.ts
  packages/tool/packages/drawing/children/baseChart/test/index.test.ts
  packages/tool/packages/duckduckgo/children/search/src/index.ts
  packages/tool/packages/duckduckgo/children/search/test/index.test.ts
  src/contract/openapi.ts
  src/index.ts
  vitest.config.ts
Labels: size/M

#29 dev
  .github/workflows/build-image-preview.yml
  .github/workflows/build-image.yml
Labels: size/S

#31 fix: smtpEmail tool
  packages/tool/packages/dalle3/config.ts
  packages/tool/packages/smtpEmail/config.ts
  packages/tool/packages/smtpEmail/src/index.ts
  packages/tool/type/fastgpt.ts
Labels: size/L

#35 perf: input type list
  eslint.config.js
  packages/tool/api/run.ts
  packages/tool/init.ts
  packages/tool/packages/Doc2X/children/PDF2text/config.ts
  packages/tool/packages/Doc2X/children/PDF2text/src/index.ts
  packages/tool/packages/bing/config.ts
  packages/tool/packages/duckduckgo/children/search/config.ts
  packages/tool/packages/duckduckgo/children/searchImg/config.ts
  packages/tool/packages/duckduckgo/children/searchNews/config.ts
  packages/tool/packages/duckduckgo/children/searchVideo/config.ts
  packages/tool/packages/duckduckgo/search/config.ts
  packages/tool/packages/duckduckgo/search/index.ts
  packages/tool/packages/duckduckgo/search/src/index.ts
  packages/tool/packages/duckduckgo/search/test/index.test.ts
  packages/tool/packages/duckduckgo/searchImg/config.ts
  packages/tool/packages/duckduckgo/searchImg/index.ts
  packages/tool/packages/duckduckgo/searchImg/src/index.ts
  packages/tool/packages/duckduckgo/searchImg/test/index.test.ts
  packages/tool/packages/duckduckgo/searchNews/config.ts
  packages/tool/packages/duckduckgo/searchNews/index.ts
  packages/tool/packages/duckduckgo/searchNews/src/index.ts
  packages/tool/packages/duckduckgo/searchNews/test/index.test.ts
  packages/tool/packages/duckduckgo/searchVideo/config.ts
  packages/tool/packages/duckduckgo/searchVideo/index.ts
  packages/tool/packages/duckduckgo/searchVideo/src/index.ts
  packages/tool/packages/duckduckgo/searchVideo/test/index.test.ts
  packages/tool/packages/fetchUrl/config.ts
  packages/tool/packages/google/config.ts
  packages/tool/packages/searchXNG/config.ts
  packages/tool/packages/wiki/config.ts
  packages/tool/utils/markdown.ts
  packages/tool/utils/string.ts
  src/utils/log.ts
  src/utils/string.ts
  src/worker/index.ts
  src/worker/type.ts
  src/worker/worker.ts
Labels: size/XXL

#36 action
  .github/workflows/build-image-preview.yml
  .github/workflows/build-image.yml
  src/utils/log.ts
  src/worker/index.ts
Labels: size/M

#37 dev
  .github/workflows/build-image-preview.yml
  docker-compose.yaml
Labels: size/M

#38 fix: workflow
  .github/workflows/build-image-preview.yml
Labels: size/S

#41 fix: delay type
  .env.template
  .github/workflows/build-image-preview.yml
  packages/tool/packages/delay/config.ts
  packages/tool/packages/delay/src/index.ts
  packages/tool/utils/tool.ts
Labels: size/M

#43 fix: action
  .github/workflows/build-image-preview.yml
Labels: size/XS

#44 0.1 dev
  .env.template
  bun.lock
  docker-compose.yaml
  package.json
  packages/tool/packages/delay/config.ts
  packages/tool/packages/delay/src/index.ts
  packages/tool/packages/drawing/children/baseChart/src/index.ts
  src/s3/config.ts
  src/s3/controller.ts
Labels: size/M

#45 chore: build worker before dev
  scripts/dev.ts
Labels: size/XS

#46 chore: add logos
  scripts/newTool/template/tool/logo.svg
  scripts/newTool/template/toolSet/config.ts
  scripts/newTool/template/toolSet/logo.svg
Labels: size/M

#47 simple config.ts
  packages/tool/packages/DingTalkWebhook/config.ts
  packages/tool/packages/Doc2X/children/PDF2text/config.ts
  packages/tool/packages/bing/config.ts
  packages/tool/packages/dalle3/config.ts
  packages/tool/packages/databaseConnection/config.ts
  packages/tool/packages/drawing/children/baseChart/config.ts
  packages/tool/packages/feishu/config.ts
  packages/tool/packages/fetchUrl/config.ts
  packages/tool/packages/google/config.ts
  packages/tool/packages/searchXNG/config.ts
  packages/tool/packages/smtpEmail/config.ts
  packages/tool/type/fastgpt.ts
  src/utils/log.ts
Labels: size/L

#53 chore: remove useless test cases.
  packages/tool/packages/DingTalkWebhook/test/index.test.ts
  packages/tool/packages/Doc2X/children/PDF2text/test/index.test.ts
  packages/tool/packages/WeWorkWebhook/test/index.test.ts
  packages/tool/packages/bing/test/index.test.ts
  packages/tool/packages/dalle3/test/index.test.ts
  packages/tool/packages/databaseConnection/test/index.test.ts
  packages/tool/packages/delay/test/index.test.ts
  packages/tool/packages/drawing/children/baseChart/test/index.test.ts
  packages/tool/packages/duckduckgo/children/search/test/index.test.ts
  packages/tool/packages/duckduckgo/children/searchNews/test/index.test.ts
  packages/tool/packages/duckduckgo/children/searchVideo/test/index.test.ts
  packages/tool/packages/feishu/test/index.test.ts
  packages/tool/packages/fetchUrl/test/index.test.ts
  packages/tool/packages/firecrawl/children/scrape/test/index.test.ts
  packages/tool/packages/firecrawl/package.json
  packages/tool/packages/getTime/test/index.test.ts
  packages/tool/packages/google/test/index.test.ts
  packages/tool/packages/mathExprVal/test/index.test.ts
  packages/tool/packages/searchXNG/test/index.test.ts
  packages/tool/packages/smtpEmail/test/index.test.ts
  packages/tool/packages/wiki/test/index.test.ts
  packages/tool/utils/tool.ts
  public/imgs/tools/firecrawl.svg
  scripts/newTool/template/tool/config.ts
  scripts/newTool/template/tool/test/index.test.ts
  scripts/newTool/template/toolSet/children/tool/test/index.test.ts
  scripts/newTool/template/toolSet/config.ts
  test/utils.ts
Labels: size/XL

#55 docs: update
  README.zh_CN.md
  docs/contribute_system_tool.md
  docs/contribute_system_tool.zh_CN.md
  public/imgs/tools/firecrawl.svg
Labels: size/S

#56 docs: update
  docs/design_document.md
  docs/design_document.zh_CN.md
Labels: size/XS

#49 New-plugin
  bun.lock
  packages/tool/packages/Doc2X/config.ts
  packages/tool/packages/GitHub/children/repositoryInfoQuery/config.ts
  packages/tool/packages/GitHub/children/repositoryInfoQuery/index.ts
  packages/tool/packages/GitHub/children/repositoryInfoQuery/src/index.ts
  packages/tool/packages/GitHub/children/userInfoQuery/config.ts
  packages/tool/packages/GitHub/children/userInfoQuery/index.ts
  packages/tool/packages/GitHub/children/userInfoQuery/src/index.ts
  packages/tool/packages/GitHub/config.ts
  packages/tool/packages/GitHub/index.ts
  packages/tool/packages/GitHub/logo.svg
  packages/tool/packages/GitHub/package.json
  packages/tool/packages/arxiv/children/abstractExtraction/config.ts
  packages/tool/packages/arxiv/children/abstractExtraction/index.ts
  packages/tool/packages/arxiv/children/abstractExtraction/src/index.ts
  packages/tool/packages/arxiv/children/arxivIDSearch/config.ts
  packages/tool/packages/arxiv/children/arxivIDSearch/index.ts
  packages/tool/packages/arxiv/children/arxivIDSearch/src/index.ts
  packages/tool/packages/arxiv/children/authorSearch/config.ts
  packages/tool/packages/arxiv/children/authorSearch/index.ts
  packages/tool/packages/arxiv/children/authorSearch/src/index.ts
  packages/tool/packages/arxiv/children/keywordSearch/config.ts
  packages/tool/packages/arxiv/children/keywordSearch/index.ts
  packages/tool/packages/arxiv/children/keywordSearch/src/index.ts
  packages/tool/packages/arxiv/children/metadataExtraction/config.ts
  packages/tool/packages/arxiv/children/metadataExtraction/index.ts
  packages/tool/packages/arxiv/children/metadataExtraction/src/index.ts
  packages/tool/packages/arxiv/config.ts
  packages/tool/packages/arxiv/index.ts
  packages/tool/packages/arxiv/logo.svg
  packages/tool/packages/arxiv/package.json
  packages/tool/packages/drawing/config.ts
  packages/tool/packages/duckduckgo/config.ts
  packages/tool/packages/firecrawl/logo.svg
  packages/tool/packages/getTime/config.ts
  packages/tool/packages/silliconFlow/children/paint/config.ts
  packages/tool/packages/silliconFlow/children/paint/index.ts
  packages/tool/packages/silliconFlow/children/paint/src/index.ts
  packages/tool/packages/silliconFlow/children/wanAi/config.ts
  packages/tool/packages/silliconFlow/children/wanAi/index.ts
  packages/tool/packages/silliconFlow/children/wanAi/src/index.ts
  packages/tool/packages/silliconFlow/config.ts
  packages/tool/packages/silliconFlow/index.ts
  packages/tool/packages/silliconFlow/logo.svg
  packages/tool/packages/silliconFlow/package.json
  public/imgs/tools/GitHub.svg
  public/imgs/tools/arxiv.svg
  public/imgs/tools/silliconFlow.svg
Labels: size/XXL

#57 doc
  .gitignore
  packages/tool/init.ts
  packages/tool/packages/GitHub/config.ts
  packages/tool/packages/silliconFlow/config.ts
  public/imgs/tools/GitHub.svg
  public/imgs/tools/SearchApi.svg
  public/imgs/tools/arxiv.svg
  public/imgs/tools/firecrawl.svg
  public/imgs/tools/silliconFlow.svg
Labels: size/M

#59 update package name
  packages/tool/init.ts
  packages/tool/packages/firecrawl/config.ts
  packages/tool/packages/silliconFlow/children/paint/config.ts
  scripts/build.ts
  src/utils/log.ts
Labels: size/S

#64 update
  packages/tool/packages/silliconFlow/children/paint/config.ts
  packages/tool/packages/silliconFlow/children/paint/src/index.ts
  packages/tool/packages/silliconFlow/children/wanAi/config.ts
  packages/tool/packages/silliconFlow/children/wanAi/src/index.ts
Labels: size/M

#65 update ignore
  .gitignore
  Dockerfile
Labels: size/XS
