Repository labring/fastgpt-plugin, pull requests merged in 2025-07, with the labels that each got.

#67 chore: support tsc check; add OutputType parse.
  Dockerfile
  package.json
  packages/tool/contract.ts
  packages/tool/packages/DingTalkWebhook/index.ts
  packages/tool/packages/Doc2X/children/PDF2text/index.ts
  packages/tool/packages/WeWorkWebhook/index.ts
  packages/tool/packages/arxiv/children/abstractExtraction/index.ts
  packages/tool/packages/arxiv/children/arxivIDSearch/index.ts
  packages/tool/packages/arxiv/children/authorSearch/index.ts
  packages/tool/packages/arxiv/children/keywordSearch/index.ts
  packages/tool/packages/arxiv/children/metadataExtraction/index.ts
  packages/tool/packages/bing/index.ts
  packages/tool/packages/dalle3/index.ts
  packages/tool/packages/databaseConnection/index.ts
  packages/tool/packages/delay/index.ts
  packages/tool/packages/drawing/children/baseChart/index.ts
  packages/tool/packages/duckduckgo/children/search/index.ts
  packages/tool/packages/duckduckgo/children/searchImg/index.ts
  packages/tool/packages/duckduckgo/children/searchNews/index.ts
  packages/tool/packages/duckduckgo/children/searchVideo/index.ts
  packages/tool/packages/feishu/index.ts
  packages/tool/packages/fetchUrl/index.ts
  packages/tool/packages/firecrawl/children/scrape/index.ts
  packages/tool/packages/getTime/index.ts
  packages/tool/packages/github/children/repositoryInfoQuery/index.ts
  packages/tool/packages/github/children/userInfoQuery/index.ts
  packages/tool/packages/google/index.ts
  packages/tool/packages/mathExprVal/index.ts
  packages/tool/packages/searchApi/children/baiduSearch/index.ts
  packages/tool/packages/searchApi/children/googleImagesSearch/index.ts
  packages/tool/packages/searchApi/children/googleNewsSearch/index.ts
  packages/tool/packages/searchApi/children/googleSearch/index.ts
  packages/tool/packages/searchApi/children/googleVideosSearch/index.ts
  packages/tool/packages/searchXNG/index.ts
  packages/tool/packages/silliconFlow/children/paint/index.ts
  packages/tool/packages/silliconFlow/children/wanAi/index.ts
  packages/tool/packages/smtpEmail/index.ts
  packages/tool/packages/wiki/index.ts
  packages/tool/utils/tool.ts
  scripts/newTool/template/tool/index.ts
  scripts/newTool/template/toolSet/children/tool/index.ts
Labels: size/L

#69 Fix-type
  packages/tool/packages/silliconFlow/children/paint/src/index.ts
  packages/tool/packages/silliconFlow/children/wanAi/src/index.ts
Labels: size/S

#73 feat: enhance S3Service initialization and bucket management
  src/index.ts
  src/s3/config.ts
  src/s3/controller.ts
Labels: size/M

#74 0.1 dev
  docs/contribute_system_tool.md
  docs/contribute_system_tool.zh_CN.md
  packages/tool/packages/Doc2X/children/PDF2text/config.ts
  packages/tool/packages/bing/config.ts
  packages/tool/packages/dalle3/config.ts
  packages/tool/packages/databaseConnection/config.ts
  packages/tool/packages/firecrawl/children/scrape/config.ts
  packages/tool/packages/github/children/repositoryInfoQuery/config.ts
  packages/tool/packages/github/children/userInfoQuery/config.ts
  packages/tool/packages/google/config.ts
  packages/tool/packages/searchApi/children/baiduSearch/config.ts
  packages/tool/packages/searchApi/children/googleImagesSearch/config.ts
  packages/tool/packages/searchApi/children/googleNewsSearch/config.ts
  packages/tool/packages/searchApi/children/googleSearch/config.ts
  packages/tool/packages/searchApi/children/googleVideosSearch/config.ts
  packages/tool/packages/searchXNG/config.ts
  packages/tool/packages/silliconFlow/children/paint/config.ts
  packages/tool/packages/silliconFlow/children/paint/src/index.ts
  packages/tool/packages/silliconFlow/children/wanAi/config.ts
  packages/tool/packages/silliconFlow/children/wanAi/src/index.ts
  packages/tool/packages/silliconFlow/config.ts
  packages/tool/packages/smtpEmail/config.ts
  packages/tool/type/fastgpt.ts
  scripts/newTool/template/tool/config.ts
  scripts/newTool/template/tool/src/index.ts
  scripts/newTool/template/toolSet/children/tool/config.ts
  scripts/newTool/template/toolSet/children/tool/src/index.ts
Labels: size/L

#79 bocha
  modules/tool/packages/bocha/config.ts
  modules/tool/packages/bocha/index.ts
  modules/tool/packages/bocha/package.json
  modules/tool/packages/bocha/src/index.ts
  modules/tool/packages/bocha/test/index.test.ts
Labels: size/L

#80 fix(typo): custom endpoint variable name
  .env.template
  env.d.ts
  src/s3/controller.ts
Labels: size/S

#83 docs: Development Specifications
  README.md
  README_zh_CN.md
  dev.md
  dev_zh_CN.md
Labels: size/L

#85 perf: adapt dalle3
  modules/tool/packages/bocha/package.json
  modules/tool/packages/dalle3/src/index.ts
Labels: size/S

#89 rename
  modules/tool/packages/feishu/config.ts
Labels: size/XS

#84 Alihundred
  bun.lock
  modules/tool/packages/aliModelStudio/children/flux/config.ts
  modules/tool/packages/aliModelStudio/children/flux/index.ts
  modules/tool/packages/aliModelStudio/children/flux/src/index.ts
  modules/tool/packages/aliModelStudio/children/flux/test/index.test.ts
  modules/tool/packages/aliModelStudio/children/wanxTxt2ImgV2/config.ts
  modules/tool/packages/aliModelStudio/children/wanxTxt2ImgV2/index.ts
  modules/tool/packages/aliModelStudio/children/wanxTxt2ImgV2/src/index.ts
  modules/tool/packages/aliModelStudio/children/wanxTxt2ImgV2/test/index.test.ts
  modules/tool/packages/aliModelStudio/config.ts
  modules/tool/packages/aliModelStudio/index.ts
  modules/tool/packages/aliModelStudio/logo.svg
  modules/tool/packages/aliModelStudio/package.json
Labels: size/XL

#93 perf: toolset children & input config
  bun.lock
  modules/tool/init.ts
  modules/tool/packages/Doc2X/children/PDF2text/config.ts
  modules/tool/packages/Doc2X/config.ts
  modules/tool/packages/aliModelStudio/children/flux/config.ts
  modules/tool/packages/aliModelStudio/children/wanxTxt2ImgV2/config.ts
  modules/tool/packages/aliModelStudio/config.ts
  modules/tool/packages/aliModelStudio/package.json
  modules/tool/packages/arxiv/config.ts
  modules/tool/packages/bing/config.ts
  modules/tool/packages/bocha/config.ts
  modules/tool/packages/dalle3/config.ts
  modules/tool/packages/databaseConnection/config.ts
  modules/tool/packages/drawing/config.ts
  modules/tool/packages/duckduckgo/config.ts
  modules/tool/packages/firecrawl/children/scrape/config.ts
  modules/tool/packages/firecrawl/config.ts
  modules/tool/packages/github/children/repositoryInfoQuery/config.ts
  modules/tool/packages/github/children/userInfoQuery/config.ts
  modules/tool/packages/github/config.ts
  modules/tool/packages/google/config.ts
  modules/tool/packages/searchApi/children/baiduSearch/config.ts
  modules/tool/packages/searchApi/children/googleImagesSearch/config.ts
  modules/tool/packages/searchApi/config.ts
  modules/tool/packages/silliconFlow/config.ts
  modules/tool/type/tool.ts
  modules/tool/utils/tool.ts
  package.json
  scripts/newTool/template/toolSet/config.ts
  scripts/plugin.ts
Labels: size/XL

#91 Blackforestlab
  modules/tool/packages/blackForestLab/children/kontextEditing/config.ts
  modules/tool/packages/blackForestLab/children/kontextEditing/index.ts
  modules/tool/packages/blackForestLab/children/kontextEditing/src/index.ts
  modules/tool/packages/blackForestLab/children/kontextEditing/test/index.test.ts
  modules/tool/packages/blackForestLab/children/kontextGeneration/config.ts
  modules/tool/packages/blackForestLab/children/kontextGeneration/index.ts
  modules/tool/packages/blackForestLab/children/kontextGeneration/src/index.ts
  modules/tool/packages/blackForestLab/children/kontextGeneration/test/index.test.ts
  modules/tool/packages/blackForestLab/config.ts
  modules/tool/packages/blackForestLab/index.ts
  modules/tool/packages/blackForestLab/logo.svg
  modules/tool/packages/blackForestLab/package.json
Labels: size/XL

#94 chore: remove children of blackForestLab
  modules/tool/packages/blackForestLab/config.ts
Labels: size/XS

#82 feat(jinaAi): 新增 Jina AI 工具集包含搜索和网页解析功能
  modules/tool/packages/jinaAi/children/jinaAiReader/config.ts
  modules/tool/packages/jinaAi/children/jinaAiReader/index.ts
  modules/tool/packages/jinaAi/children/jinaAiReader/src/index.ts
  modules/tool/packages/jinaAi/children/jinaAiSearch/config.ts
  modules/tool/packages/jinaAi/children/jinaAiSearch/index.ts
  modules/tool/packages/jinaAi/children/jinaAiSearch/src/index.ts
  modules/tool/packages/jinaAi/config.ts
  modules/tool/packages/jinaAi/index.ts
  modules/tool/packages/jinaAi/logo.svg
  modules/tool/packages/jinaAi/package.json
Labels: size/XL

#95 Fix sil
  modules/tool/packages/silliconFlow/children/paint/src/index.ts
Labels: size/M

#102 perf: sillicon tool
  modules/tool/packages/blackForestLab/package.json
  modules/tool/packages/searchApi/children/baiduSearch/config.ts
  modules/tool/packages/searchApi/children/googleImagesSearch/config.ts
  modules/tool/packages/searchApi/children/googleNewsSearch/config.ts
  modules/tool/packages/searchApi/children/googleSearch/config.ts
  modules/tool/packages/searchApi/children/googleVideosSearch/config.ts
  modules/tool/packages/silliconFlow/children/paint/config.ts
  modules/tool/packages/silliconFlow/children/paint/src/index.ts
  modules/tool/packages/silliconFlow/children/wanAi/config.ts
  modules/tool/packages/silliconFlow/children/wanAi/src/index.ts
Labels: size/M

#105 Refactor stream message types to use enums for improved clarity and …
  modules/tool/api/runStream.ts
  modules/tool/type/stream.ts
  modules/tool/type/tool.ts
  modules/tool/utils/stream.ts
  modules/tool/utils/tool.ts
  sdk/client.ts
  sdk/runToolStream.ts
  src/worker/index.ts
Labels: size/L

#107 perf(dev): support build specific tool; perf tool name validation
  bun.lock
  modules/tool/packages/DingTalkWebhook/package.json
  modules/tool/packages/Doc2X/package.json
  modules/tool/packages/WeWorkWebhook/package.json
  modules/tool/packages/aliModelStudio/package.json
  modules/tool/packages/arxiv/package.json
  modules/tool/packages/bing/package.json
  modules/tool/packages/blackForestLab/package.json
  modules/tool/packages/bocha/package.json
  modules/tool/packages/dalle3/package.json
  modules/tool/packages/databaseConnection/package.json
  modules/tool/packages/delay/package.json
  modules/tool/packages/drawing/package.json
  modules/tool/packages/duckduckgo/package.json
  modules/tool/packages/feishu/package.json
  modules/tool/packages/fetchUrl/package.json
  modules/tool/packages/firecrawl/package.json
  modules/tool/packages/getTime/package.json
  modules/tool/packages/github/package.json
  modules/tool/packages/google/package.json
  modules/tool/packages/jinaAi/package.json
  modules/tool/packages/mathExprVal/package.json
  modules/tool/packages/searchApi/package.json
  modules/tool/packages/searchXNG/package.json
  modules/tool/packages/silliconFlow/package.json
  modules/tool/packages/smtpEmail/package.json
  modules/tool/packages/wiki/package.json
  scripts/build.ts
  scripts/newFile.ts
  scripts/newTool/index.ts
  scripts/newTool/template/tool/package.json
  scripts/newTool/template/toolSet/package.json
Labels: size/L

#108 chore: build & doc
  dev.md
  dev_zh_CN.md
  modules/tool/packages/dalle3/src/index.ts
  modules/tool/packages/drawing/children/baseChart/src/index.ts
  modules/tool/utils/index.ts
  modules/tool/utils/request.ts
  modules/tool/utils/uploadFile.ts
  scripts/build.ts
Labels: size/L

#109 fix: build script
  scripts/build.ts
Labels: size/S

#114 feat: support system-toolset
  modules/tool/packages/Doc2X/children/PDF2text/config.ts
  modules/tool/packages/Doc2X/config.ts
  modules/tool/packages/aliModelStudio/children/flux/config.ts
  modules/tool/packages/aliModelStudio/children/wanxTxt2ImgV2/config.ts
  modules/tool/packages/aliModelStudio/config.ts
  modules/tool/packages/blackForestLab/children/kontextEditing/config.ts
  modules/tool/packages/blackForestLab/children/kontextGeneration/config.ts
  modules/tool/packages/blackForestLab/config.ts
  modules/tool/packages/firecrawl/children/scrape/config.ts
  modules/tool/packages/firecrawl/config.ts
  modules/tool/packages/github/children/repositoryInfoQuery/config.ts
  modules/tool/packages/github/children/userInfoQuery/config.ts
  modules/tool/packages/github/config.ts
  modules/tool/packages/jinaAi/children/jinaAiReader/config.ts
  modules/tool/packages/jinaAi/children/jinaAiSearch/config.ts
  modules/tool/packages/jinaAi/config.ts
  modules/tool/packages/searchApi/children/baiduSearch/config.ts
  modules/tool/packages/searchApi/children/googleImagesSearch/config.ts
  modules/tool/packages/searchApi/children/googleNewsSearch/config.ts
  modules/tool/packages/searchApi/children/googleSearch/config.ts
  modules/tool/packages/searchApi/children/googleVideosSearch/config.ts
  modules/tool/packages/searchApi/config.ts
  modules/tool/packages/silliconFlow/children/paint/config.ts
  modules/tool/packages/silliconFlow/children/wanAi/config.ts
  modules/tool/packages/silliconFlow/config.ts
  modules/tool/type/api.ts
  modules/tool/type/index.ts
  modules/tool/type/tool.ts
  modules/tool/utils/tool.ts
  sdk/.gitignore
Labels: size/L

#116 Revert "fix: s3 init do not throw when can not set bucket policy"
  src/index.ts
  src/s3/controller.ts
  src/utils/catch.ts
Labels: size/M

#117 fix: build
  scripts/build.ts
Labels: size/XS

#128 fix: update video results handling to ensure URLs are correctly extracted
  modules/tool/packages/silliconFlow/children/wanAi/src/index.ts
Labels: size/XS

#130 fix: read file
  bun.lock
  modules/tool/packages/officeGenerate/config.ts
  modules/tool/packages/officeGenerate/index.ts
  modules/tool/packages/officeGenerate/logo.svg
  modules/tool/packages/officeGenerate/package.json
  modules/tool/packages/officeGenerate/src/docx.ts
  modules/tool/packages/officeGenerate/src/index.ts
  modules/tool/packages/officeGenerate/src/xlsx.ts
  modules/tool/packages/officeGenerate/test/index.test.ts
  scripts/build.ts
Labels: size/XXL

#121 perf: plugin error catch (#120)
  modules/tool/packages/Doc2X/children/PDF2text/config.ts
  modules/tool/packages/aliModelStudio/children/flux/config.ts
  modules/tool/packages/aliModelStudio/children/flux/src/index.ts
  modules/tool/packages/aliModelStudio/children/wanxTxt2ImgV2/config.ts
  modules/tool/packages/aliModelStudio/children/wanxTxt2ImgV2/src/index.ts
  modules/tool/packages/blackForestLab/children/kontextEditing/config.ts
  modules/tool/packages/blackForestLab/children/kontextEditing/src/index.ts
  modules/tool/packages/blackForestLab/children/kontextGeneration/config.ts
  modules/tool/packages/blackForestLab/children/kontextGeneration/src/index.ts
  modules/tool/packages/bocha/config.ts
  modules/tool/packages/bocha/src/index.ts
  modules/tool/packages/dalle3/config.ts
  modules/tool/packages/dalle3/src/index.ts
  modules/tool/packages/searchXNG/config.ts
  modules/tool/packages/searchXNG/src/index.ts
  modules/tool/type/fastgpt.ts
  modules/tool/type/tool.ts
  modules/tool/utils/index.ts
  modules/tool/utils/tool.ts
  sdk/package.json
  src/worker/index.ts
  src/worker/type.ts
  src/worker/worker.ts
Labels: size/L

#126 implement upload and delete API for tools
  .env.template
  bun.lock
  env.d.ts
  modules/tool/api/delete.ts
  modules/tool/api/upload.ts
  modules/tool/contract.ts
  modules/tool/init.ts
  modules/tool/router.ts
  modules/tool/type/api.ts
  modules/tool/type/tool.ts
  modules/tool/utils/tool.ts
  package.json
  scripts/build.ts
  scripts/dev.ts
  src/index.ts
  src/plugin/model.ts
  src/s3/config.ts
  src/s3/controller.ts
  src/utils/mongo.ts
  src/utils/string.ts
  src/worker/worker.ts
Labels: size/XL

#136 fix:change url of doc
  README.md
  README_zh_CN.md
  modules/tool/packages/searchXNG/config.ts
Labels: size/S

#132 feat: support system-toolset (#114)
  bun.lock
  modules/tool/packages/Doc2X/children/PDF2text/config.ts
  modules/tool/packages/Doc2X/config.ts
  modules/tool/packages/aliModelStudio/children/flux/config.ts
  modules/tool/packages/aliModelStudio/children/wanxTxt2ImgV2/config.ts
  modules/tool/packages/aliModelStudio/config.ts
  modules/tool/packages/bing/config.ts
  modules/tool/packages/blackForestLab/children/kontextEditing/config.ts
  modules/tool/packages/blackForestLab/children/kontextGeneration/config.ts
  modules/tool/packages/blackForestLab/config.ts
  modules/tool/packages/bocha/config.ts
  modules/tool/packages/dalle3/config.ts
  modules/tool/packages/databaseConnection/config.ts
  modules/tool/packages/firecrawl/children/scrape/config.ts
  modules/tool/packages/firecrawl/config.ts
  modules/tool/packages/github/children/repositoryInfoQuery/config.ts
  modules/tool/packages/github/children/userInfoQuery/config.ts
  modules/tool/packages/github/config.ts
  modules/tool/packages/google/config.ts
  modules/tool/packages/jinaAi/children/jinaAiReader/config.ts
  modules/tool/packages/jinaAi/children/jinaAiSearch/config.ts
  modules/tool/packages/jinaAi/config.ts
  modules/tool/packages/libulibu/children/star3/config.ts
  modules/tool/packages/libulibu/config.ts
  modules/tool/packages/searchApi/children/baiduSearch/config.ts
  modules/tool/packages/searchApi/children/googleImagesSearch/config.ts
  modules/tool/packages/searchApi/children/googleNewsSearch/config.ts
  modules/tool/packages/searchApi/children/googleSearch/config.ts
  modules/tool/packages/searchApi/children/googleVideosSearch/config.ts
  modules/tool/packages/searchApi/config.ts
  modules/tool/packages/silliconFlow/children/paint/config.ts
  modules/tool/packages/silliconFlow/children/wanAi/config.ts
  modules/tool/packages/silliconFlow/config.ts
  modules/tool/type/api.ts
  modules/tool/type/index.ts
  modules/tool/type/tool.ts
  modules/tool/utils/tool.ts
  scripts/newTool/template/tool/config.ts
  scripts/newTool/template/toolSet/children/tool/config.ts
  scripts/newTool/template/toolSet/config.ts
  sdk/.gitignore
  sdk/package.json
  src/contract/client.ts
Labels: size/XXL

#140 feat: integrate Signoz for monitoring and logging tools
  .env.template
  bun.lock
  modules/tool/api/runStream.ts
  package.json
  src/constants/signoz.ts
  src/index.ts
  src/utils/log.ts
  src/utils/signoz.ts
Labels: size/L

#144 fix: mathExprVal
  modules/tool/packages/mathExprVal/src/index.ts
Labels: size/XS

#146 fix: markdown transform
  bun.lock
  modules/tool/packages/markdownTransform/test/index.test.ts
  modules/tool/utils/tool.ts
Labels: size/XL
