Repository labring/fastgpt-plugin, pull requests merged in 2025-09, with the labels that each got.

#170 fix: smtpEmail to, cc, bcc Type parse
  modules/tool/packages/smtpEmail/src/index.ts
Labels: size/M

#169 feat: add Sangfor model provider and API endpoint
  modules/model/api/provider.ts
  modules/model/constants.ts
  modules/model/contract.ts
  modules/model/provider/Sangfor/logo.svg
  modules/model/router.ts
  sdk/client.ts
Labels: size/M

#173 fix: type
  modules/model/contract.ts
  modules/tool/packages/Doc2X/children/PDF2text/src/index.ts
Labels: size/XS

#177 tool type
  modules/tool/contract.ts
  modules/tool/controller.ts
  modules/tool/type/tool.ts
  sdk/client.ts
  sdk/package.json
Labels: size/S

#166 feat: workflow templates
  modules/tool/contract.ts
  modules/tool/type/api.ts
  modules/tool/utils/icon.ts
  modules/workflow/api/getTemplateList.ts
  modules/workflow/contract.ts
  modules/workflow/init.ts
  modules/workflow/router.ts
  modules/workflow/templates/CQ.json
  modules/workflow/templates/Chinese.json
  modules/workflow/templates/TranslateRobot.json
  modules/workflow/templates/animalLife.json
  modules/workflow/templates/chatGuide.json
  modules/workflow/templates/divination.json
  modules/workflow/templates/flux.json
  modules/workflow/templates/githubIssue.json
  modules/workflow/templates/google.json
  modules/workflow/templates/longTranslate.json
  modules/workflow/templates/plugin-dalle.json
  modules/workflow/templates/plugin-feishu.json
  modules/workflow/templates/simpleDatasetChat.json
  modules/workflow/templates/srt-translate.json
  modules/workflow/templates/stock.json
  modules/workflow/templates/timeBot.json
  modules/workflow/type.ts
  scripts/build.ts
  scripts/dev.ts
  sdk/client.ts
  sdk/package.json
  src/contract/client.ts
  src/contract/index.ts
  src/index.ts
  src/router/index.ts
  tsconfig.json
Labels: size/XXL

#180 remove empty
  modules/model/provider/Moonshot/index.ts
Labels: size/XS

#183 feat: add tool searchInfinity
  modules/tool/packages/searchInfinity/config.ts
  modules/tool/packages/searchInfinity/index.ts
  modules/tool/packages/searchInfinity/logo.svg
  modules/tool/packages/searchInfinity/package.json
  modules/tool/packages/searchInfinity/src/index.ts
  modules/tool/packages/searchInfinity/test/index.test.ts
Labels: size/XL

#185 perf: searchinfinity code
  dev_zh_CN.md
  modules/tool/packages/searchInfinity/config.ts
  modules/tool/packages/searchInfinity/src/index.ts
Labels: size/M

#171 feat: hot swapping
  .env.template
  bun.lock
  env.d.ts
  modules/model/init.ts
  modules/tool/api/delete.ts
  modules/tool/api/list.ts
  modules/tool/api/upload.ts
  modules/tool/constants.ts
  modules/tool/contract.ts
  modules/tool/controller.ts
  modules/tool/init.ts
  modules/tool/packages/metaso/children/metasoSearch/config.ts
  modules/tool/router.ts
  modules/tool/type/api.ts
  modules/tool/type/tool.ts
  modules/tool/utils/tool.ts
  package.json
  scripts/build.ts
  scripts/dev.ts
  scripts/devServer.ts
  sdk/client.ts
  sdk/package.json
  src/cache/index.ts
  src/cache/init.ts
  src/cache/type.ts
  src/index.ts
  src/mongo/index.ts
  src/mongo/models/plugins.ts
  src/mongo/utils.ts
  src/redis/index.ts
  src/s3/config.ts
  src/s3/const.ts
  src/s3/controller.ts
  src/utils/string.ts
  src/worker/index.ts
  src/worker/worker.ts
  tsconfig.json
Labels: size/XXL

#193 fix: use external base url when generate post url
  .env.template
  modules/tool/api/upload/confirmUpload.ts
  modules/tool/controller.ts
  modules/tool/init.ts
  src/cache/index.ts
  src/s3/controller.ts
  src/s3/index.ts
Labels: size/M

#192 V0.2 dev
  .env.template
  .gitignore
  bun.lock
  env.d.ts
  modules/model/init.ts
  modules/tool/api/list.ts
  modules/tool/api/upload/confirmUpload.ts
  modules/tool/api/upload/delete.ts
  modules/tool/api/upload/getUploadURL.ts
  modules/tool/api/upload/router.ts
  modules/tool/constants.ts
  modules/tool/contract.ts
  modules/tool/controller.ts
  modules/tool/cronTask/cleanOrphanPlugins.ts
  modules/tool/cronTask/index.ts
  modules/tool/init.ts
  modules/tool/packages/fetchUrl/src/index.ts
  modules/tool/packages/metaso/children/metasoSearch/config.ts
  modules/tool/router.ts
  modules/tool/type/api.ts
  modules/tool/type/tool.ts
  modules/tool/utils.ts
  modules/tool/utils/tool.ts
  modules/tool/utils/uploadFile.ts
  package.json
  scripts/build.ts
  scripts/dev.ts
  scripts/devServer.ts
  sdk/client.ts
  sdk/package.json
  src/cache/index.ts
  src/cache/init.ts
  src/cache/type.ts
  src/index.ts
  src/mongo/index.ts
  src/mongo/models/plugins.ts
  src/mongo/utils.ts
  src/redis/index.ts
  src/redis/lock.ts
  src/s3/config.ts
  src/s3/const.ts
  src/s3/controller.ts
  src/s3/index.ts
  src/s3/type.ts
  src/utils/catch.ts
  src/utils/log.ts
  src/utils/string.ts
  src/worker/index.ts
  src/worker/type.ts
  src/worker/worker.ts
  tsconfig.json
Labels: size/XXL

#194 feat: add base64 to image plugin
  bun.lock
  modules/tool/packages/base64ToImage/config.ts
  modules/tool/packages/base64ToImage/index.ts
  modules/tool/packages/base64ToImage/logo.svg
  modules/tool/packages/base64ToImage/package.json
  modules/tool/packages/base64ToImage/src/index.ts
  modules/tool/packages/base64ToImage/test/index.test.ts
Labels: size/L

#199 fix: worker connect mongoose causes timeout error.
  modules/tool/init.ts
  modules/tool/utils.ts
  src/worker/worker.ts
Labels: size/L

#201 feat: integrate multiple sql-like database tool set
  .gitignore
  bun.lock
  modules/tool/packages/dbops/children/clickhouse/config.ts
  modules/tool/packages/dbops/children/clickhouse/index.ts
  modules/tool/packages/dbops/children/clickhouse/logo.svg
  modules/tool/packages/dbops/children/clickhouse/src/index.ts
  modules/tool/packages/dbops/children/mysql/config.ts
  modules/tool/packages/dbops/children/mysql/index.ts
  modules/tool/packages/dbops/children/mysql/logo.svg
  modules/tool/packages/dbops/children/mysql/src/index.ts
  modules/tool/packages/dbops/children/oracle/config.ts
  modules/tool/packages/dbops/children/oracle/index.ts
  modules/tool/packages/dbops/children/oracle/logo.svg
  modules/tool/packages/dbops/children/oracle/src/index.ts
  modules/tool/packages/dbops/children/postgresql/config.ts
  modules/tool/packages/dbops/children/postgresql/index.ts
  modules/tool/packages/dbops/children/postgresql/logo.svg
  modules/tool/packages/dbops/children/postgresql/src/index.ts
  modules/tool/packages/dbops/children/sqlserver/config.ts
  modules/tool/packages/dbops/children/sqlserver/index.ts
  modules/tool/packages/dbops/children/sqlserver/logo.svg
  modules/tool/packages/dbops/children/sqlserver/src/index.ts
  modules/tool/packages/dbops/config.ts
  modules/tool/packages/dbops/index.ts
  modules/tool/packages/dbops/package.json
  modules/tool/packages/dbops/types.ts
  modules/tool/packages/searchInfinity/src/index.ts
  modules/tool/utils/icon.ts
Labels: size/XXL

#205 perf: fetch url limit size;feat: new model and base64 decode tool
  bun.lock
  modules/model/provider/DeepSeek/index.ts
  modules/model/provider/Moonshot/index.ts
  modules/model/provider/Qwen/index.ts
  modules/tool/constants.ts
  modules/tool/packages/base64Decode/children/toImage/config.ts
  modules/tool/packages/base64Decode/children/toImage/index.ts
  modules/tool/packages/base64Decode/children/toImage/src/index.ts
  modules/tool/packages/base64Decode/children/toText/config.ts
  modules/tool/packages/base64Decode/children/toText/index.ts
  modules/tool/packages/base64Decode/children/toText/src/index.ts
  modules/tool/packages/base64Decode/config.ts
  modules/tool/packages/base64Decode/index.ts
  modules/tool/packages/base64Decode/logo.svg
  modules/tool/packages/base64Decode/package.json
  modules/tool/packages/base64ToImage/test/index.test.ts
  modules/tool/packages/fetchUrl/config.ts
  modules/tool/packages/fetchUrl/src/index.ts
  src/index.ts
  src/s3/config.ts
  src/s3/controller.ts
  src/s3/index.ts
Labels: size/L

#208 fix: dbops icon; perf: refresh versionKey when service starting
  modules/tool/packages/dbops/config.ts
  modules/tool/packages/dbops/logo.svg
  modules/tool/utils.ts
  scripts/dev.ts
  src/index.ts
Labels: size/M

#209 fix: tool icon
  modules/tool/utils.ts
Labels: size/S

#203 feat: chatPPT plugin
  bun.lock
  modules/tool/packages/chatPPT/config.ts
  modules/tool/packages/chatPPT/index.ts
  modules/tool/packages/chatPPT/logo.png
  modules/tool/packages/chatPPT/package.json
  modules/tool/packages/chatPPT/src/index.ts
  modules/tool/packages/chatPPT/test/index.test.ts
Labels: size/L
